[package]
name = "search_index"
version = "0.1.0"
authors = ["qiongtubao <810776886@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.0"
notify = "4.0.13"
once_cell = "1.0"
